import { Montserrat } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.scss";
import Header from '../components/layout/Header/Header.js'
import Sidebar from '../components/layout/Sidebar/Sidebar.js'




const montserratSans = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={`${styles['main-layout']} ${montserratSans.variable}`}>
        
        <Sidebar/>

        <main className={styles['main-outlet']}>
          <Header/>
          
          <div className={styles['outlet-container']}>

            <div className={styles['outlet-header']}>

              <h2 className={styles['header-text']}>Dashboard</h2>

            </div>

            <div className={styles.outlet}>
              {children} 
            </div>
            
          </div>

           
          
        </main>
        
      </body>
    </html>
  );
}
