import { Montserrat } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.scss";

const montserratSans = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});


export const metadata = {
  title: "OnePoint Proposals",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  

  return (
    <html lang="en">
      <body className={`${styles['parent-layout']} ${montserratSans.variable}`}>

        {children}
        
      </body>
    </html>
  );
}
